# Site settings
title: Eissa Soubhi
description: 'Full-Stack Web Developer From the Kingdom of Morocco'
url: 'https://eissasoubhi.github.io'
baseurl: '/eissasoubhi'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Eissa Soubhi'
  email: eissa.soubhi@gmail.com
  twitter_username: eissa_soubhi
  github_username:  eissasoubhi
  linkedin_username:  aissa0soubhi
  skype_username: eissa.soubhi

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
